events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    include /etc/nginx/sites-enabled/*;  # Ładowanie plików konfiguracyjnych z sites-enabled

    # Możesz dodać dodatkowe ustawienia globalne, np. limity, nagłówki itp.

    # Serwer domyślny (można usunąć lub dostosować, jeśli nie jest potrzebny)
    server {
        listen 80 default_server;
        server_name _;

        # Przekierowanie błędów na stronę 404 lub inną stronę
        location / {
            return 444;  # Może to być np. przekierowanie do strony 404
        }
    }
}
