/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AuditResponse } from '../models/audit-response';
import { getAudit } from '../fn/audit-controller/get-audit';
import { GetAudit$Params } from '../fn/audit-controller/get-audit';
import { whoAmI } from '../fn/audit-controller/who-am-i';
import { WhoAmI$Params } from '../fn/audit-controller/who-am-i';

@Injectable({ providedIn: 'root' })
export class AuditControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAudit()` */
  static readonly GetAuditPath = '/api/logs';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAudit()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAudit$Response(params: GetAudit$Params, context?: HttpContext): Observable<StrictHttpResponse<AuditResponse>> {
    return getAudit(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAudit$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAudit(params: GetAudit$Params, context?: HttpContext): Observable<AuditResponse> {
    return this.getAudit$Response(params, context).pipe(
      map((r: StrictHttpResponse<AuditResponse>): AuditResponse => r.body)
    );
  }

  /** Path part for operation `whoAmI()` */
  static readonly WhoAmIPath = '/api/logs/test';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `whoAmI()` instead.
   *
   * This method doesn't expect any request body.
   */
  whoAmI$Response(params?: WhoAmI$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return whoAmI(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `whoAmI$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  whoAmI(params?: WhoAmI$Params, context?: HttpContext): Observable<string> {
    return this.whoAmI$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
