/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { fetchGuaranteesExpiresIn7Days } from '../fn/dashboard-notification-controller/fetch-guarantees-expires-in-7-days';
import { FetchGuaranteesExpiresIn7Days$Params } from '../fn/dashboard-notification-controller/fetch-guarantees-expires-in-7-days';
import { PageGuaranteeResponse } from '../models/page-guarantee-response';

@Injectable({ providedIn: 'root' })
export class DashboardNotificationControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `fetchGuaranteesExpiresIn7Days()` */
  static readonly FetchGuaranteesExpiresIn7DaysPath = '/dashboard';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `fetchGuaranteesExpiresIn7Days()` instead.
   *
   * This method doesn't expect any request body.
   */
  fetchGuaranteesExpiresIn7Days$Response(params?: FetchGuaranteesExpiresIn7Days$Params, context?: HttpContext): Observable<StrictHttpResponse<PageGuaranteeResponse>> {
    return fetchGuaranteesExpiresIn7Days(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `fetchGuaranteesExpiresIn7Days$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  fetchGuaranteesExpiresIn7Days(params?: FetchGuaranteesExpiresIn7Days$Params, context?: HttpContext): Observable<PageGuaranteeResponse> {
    return this.fetchGuaranteesExpiresIn7Days$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageGuaranteeResponse>): PageGuaranteeResponse => r.body)
    );
  }

}
