/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getUserLogsPdf } from '../fn/pdf-controller/get-user-logs-pdf';
import { GetUserLogsPdf$Params } from '../fn/pdf-controller/get-user-logs-pdf';

@Injectable({ providedIn: 'root' })
export class PdfControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getUserLogsPdf()` */
  static readonly GetUserLogsPdfPath = '/api/pdf';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUserLogsPdf()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserLogsPdf$Response(params: GetUserLogsPdf$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
    return getUserLogsPdf(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUserLogsPdf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserLogsPdf(params: GetUserLogsPdf$Params, context?: HttpContext): Observable<Blob> {
    return this.getUserLogsPdf$Response(params, context).pipe(
      map((r: StrictHttpResponse<Blob>): Blob => r.body)
    );
  }

}
