/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddGuaranteeRequest {
  brand: string;
  endDate: string;
  kindOfProduct: 'ELECTRONICS' | 'CARS' | 'CLOTHES' | 'SERVICES' | 'OTHER';
  model: string;
  notes?: string;
  startDate: string;
}
