/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuditLogsModel } from './audit-logs-model';
export interface AuditResponse {
  auditLogs?: Array<AuditLogsModel>;
  firstPage?: boolean;
  lastPage?: boolean;
  page?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
}
