/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuditLogsModel {
  logDetails?: {
[key: string]: string;
};
  logsType?: 'ADDED_GUARANTEE_HISTORY' | 'REMOVED_GUARANTEE_HISTORY' | 'RESET_PASSWORD';
  timestamp?: string;
}
