/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChangePasswordRequest {
  confirmPassword?: string;
  newPassword?: string;
  oldPassword?: string;
}
