/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateGuaranteeHistoryRequest {
  guaranteeId: number;
  guaranteeStatus: 'ACTIVE' | 'EXPIRED' | 'PENDING' | 'REJECTED' | 'APPROVED';
  notes: string;
  positiveFeedback: boolean;
}
