/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GuaranteeHistoryResponse {
  brand?: string;
  changeTime?: string;
  guaranteeStatus?: 'ACTIVE' | 'EXPIRED' | 'PENDING' | 'REJECTED' | 'APPROVED';
  id?: number;
  kindOfProduct?: 'ELECTRONICS' | 'CARS' | 'CLOTHES' | 'SERVICES' | 'OTHER';
  model?: string;
  notes?: string;
  positiveFeedback?: boolean;
}
