/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GuaranteeResponse {
  brand?: string;
  documentUrl?: string;
  endDate?: string;
  guaranteeStatus?: 'ACTIVE' | 'EXPIRED' | 'PENDING' | 'REJECTED' | 'APPROVED';
  id?: number;
  kindOfDevice?: 'ELECTRONICS' | 'CARS' | 'CLOTHES' | 'SERVICES' | 'OTHER';
  model?: string;
  notes?: string;
  startDate?: string;
}
