/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NewsArticle {
  article_id?: string;
  description?: string;
  image_url?: string;
  link?: string;
  pubDate?: string;
  title?: string;
}
