/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NewsArticle } from '../models/news-article';
export interface NewsArticleRawApi {
  results?: Array<NewsArticle>;
  status?: string;
  totalResults?: number;
}
