/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GuaranteeHistoryResponse } from './guarantee-history-response';
import { PageableObject } from './pageable-object';
import { SortObject } from './sort-object';
export interface PageGuaranteeHistoryResponse {
  content?: Array<GuaranteeHistoryResponse>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
}
