/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  enabled?: boolean;
  notificationPreference?: 'EMAIL' | 'DASHBOARD' | 'ALL';
  role?: 'USER' | 'ADMIN';
  userEmail?: string;
  userId?: number;
  userName?: string;
}
