/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuditResponse } from '../../models/audit-response';

export interface GetAudit$Params {
  email: string;
  page?: number;
  size?: number;
}

export function getAudit(http: HttpClient, rootUrl: string, params: GetAudit$Params, context?: HttpContext): Observable<StrictHttpResponse<AuditResponse>> {
  const rb = new RequestBuilder(rootUrl, getAudit.PATH, 'get');
  if (params) {
    rb.query('email', params.email, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AuditResponse>;
    })
  );
}

getAudit.PATH = '/api/logs';
