/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface EditGuaranteeStatus$Params {
  guaranteeId: number;
  guaranteeStatus: 'ACTIVE' | 'EXPIRED' | 'PENDING' | 'REJECTED' | 'APPROVED';
}

export function editGuaranteeStatus(http: HttpClient, rootUrl: string, params: EditGuaranteeStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, editGuaranteeStatus.PATH, 'put');
  if (params) {
    rb.query('guaranteeId', params.guaranteeId, {});
    rb.query('guaranteeStatus', params.guaranteeStatus, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

editGuaranteeStatus.PATH = '/api/guarantee/edit-status';
