/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface EditGuaranteeExpiration$Params {
  guaranteeId: number;
  expirationDate: string;
}

export function editGuaranteeExpiration(http: HttpClient, rootUrl: string, params: EditGuaranteeExpiration$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, editGuaranteeExpiration.PATH, 'put');
  if (params) {
    rb.query('guaranteeId', params.guaranteeId, {});
    rb.query('expirationDate', params.expirationDate, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

editGuaranteeExpiration.PATH = '/api/guarantee/edit-expiration';
