/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GuaranteeResponse } from '../../models/guarantee-response';

export interface GetGuaranteeDetails$Params {
  guaranteeId: number;
}

export function getGuaranteeDetails(http: HttpClient, rootUrl: string, params: GetGuaranteeDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<GuaranteeResponse>> {
  const rb = new RequestBuilder(rootUrl, getGuaranteeDetails.PATH, 'get');
  if (params) {
    rb.path('guaranteeId', params.guaranteeId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GuaranteeResponse>;
    })
  );
}

getGuaranteeDetails.PATH = '/api/guarantee/{guaranteeId}';
