/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserActivationResponse } from '../../models/user-activation-response';

export interface ActivateUser$Params {
  userActivationToken: string;
}

export function activateUser(http: HttpClient, rootUrl: string, params: ActivateUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UserActivationResponse>> {
  const rb = new RequestBuilder(rootUrl, activateUser.PATH, 'post');
  if (params) {
    rb.query('userActivationToken', params.userActivationToken, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserActivationResponse>;
    })
  );
}

activateUser.PATH = '/api/users/activate-user';
