/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NewsArticleRawApi } from '../../models/news-article-raw-api';

export interface GetNewsArticles$Params {
  articleParam: string;
}

export function getNewsArticles(http: HttpClient, rootUrl: string, params: GetNewsArticles$Params, context?: HttpContext): Observable<StrictHttpResponse<NewsArticleRawApi>> {
  const rb = new RequestBuilder(rootUrl, getNewsArticles.PATH, 'get');
  if (params) {
    rb.query('articleParam', params.articleParam, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NewsArticleRawApi>;
    })
  );
}

getNewsArticles.PATH = '/api/article-generator';
