spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/guarantee-manager
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: false
    change-log: db/changelog/changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  application:
    user-activation-token-characters: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
    user-activation-token-length: 6
logging:
  level:
    org.springframework.security: DEBUG
    root: info
