spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://db:5432/guarantee-manager
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master-changelog.xml

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
      jdbc:
        lob:
          non_contextual_creation: true

  application:
    user-activation-token-characters: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
    user-activation-token-length: 6
    mailing:
      frontend:
        activation-url: http://157.180.16.111:4200/activate-account

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cloudinary:
    CLOUDINARY_URL: cloudinary://${CLOUDINARY_API_KEY}:${CLOUDINARY_API_SECRET}@dbgncy44q

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
    org.springframework.security: warn
    root: info
    org.hibernate.sql: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF