spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://localhost:5434/guarantee-manager
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master-changelog.xml

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
      jdbc:
        lob:
          non_contextual_creation: true

  application:
    user-activation-token-characters: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
    user-activation-token-length: 6
    mailing:
      frontend:
        activation-url: http://localhost:4200/activate-account

  mail:
    host: localhost
    port: 1025
    username: marcinsz1993
    password: marcinsz1993
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

  cloudinary:
    CLOUDINARY_URL: cloudinary://${CLOUDINARY_API_KEY}:${CLOUDINARY_API_SECRET}@dbgncy44q

logging:
  level:
    org.springframework.security: DEBUG
    root: info
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


