/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponse } from '../../models/api-response';
import { CreateGuaranteeHistoryRequest } from '../../models/create-guarantee-history-request';

export interface AddGuaranteeChange$Params {
  createGuaranteeHistoryRequest: CreateGuaranteeHistoryRequest;
}

export function addGuaranteeChange(http: HttpClient, rootUrl: string, params: AddGuaranteeChange$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponse>> {
  const rb = new RequestBuilder(rootUrl, addGuaranteeChange.PATH, 'post');
  if (params) {
    rb.query('createGuaranteeHistoryRequest', params.createGuaranteeHistoryRequest, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponse>;
    })
  );
}

addGuaranteeChange.PATH = '/api/guarantee-history';
