/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponse } from '../../models/api-response';

export interface GetAllByGuaranteeStatus$Params {
  guaranteeStatus: 'ACTIVE' | 'EXPIRED' | 'PENDING' | 'REJECTED' | 'APPROVED';
}

export function getAllByGuaranteeStatus(http: HttpClient, rootUrl: string, params: GetAllByGuaranteeStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllByGuaranteeStatus.PATH, 'get');
  if (params) {
    rb.query('guaranteeStatus', params.guaranteeStatus, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponse>;
    })
  );
}

getAllByGuaranteeStatus.PATH = '/api/guarantee-history/status';
