/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageGuaranteeHistoryResponse } from '../../models/page-guarantee-history-response';

export interface GetAllUserGuaranteesHistories$Params {
  pageNumber?: number;
  pageSize?: number;
}

export function getAllUserGuaranteesHistories(http: HttpClient, rootUrl: string, params?: GetAllUserGuaranteesHistories$Params, context?: HttpContext): Observable<StrictHttpResponse<PageGuaranteeHistoryResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllUserGuaranteesHistories.PATH, 'get');
  if (params) {
    rb.query('pageNumber', params.pageNumber, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageGuaranteeHistoryResponse>;
    })
  );
}

getAllUserGuaranteesHistories.PATH = '/api/guarantee-history';
